### ISSUE TITLE
Checklist 2.0

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/levelup#3]
- [x] Website and it's presentation

- [x] Terms and privacy

- [x] Preview links: not on the right place.

- [x] Migrate the previews to the new

-------------
- [x] Setup notice in the popup

- [x] Change the name, prefix and text-domain

- [x] API key plugin on LevelUp
- [x] http://take.ms/CRidD - We don't need this notice.
- [x] http://take.ms/AeeYt - number prints with html

- [x] When the key is not installed it does not show the widget
